# Generated by Django 3.2.17 on 2023-02-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
