exclude: ".git|.tox"
default_stages: [commit]
fail_fast: yes

default_language_version:
    python: python3.8

repos:
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.3.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: [ '@arrai-innovations/commitlint-config' ]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer

    - repo: https://github.com/syntaqx/git-hooks
      rev: v0.0.17
      hooks:
          - id: circleci-config-validate
            files: ^.circleci/config.yml$

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black

    - repo: https://github.com/csachs/pyproject-flake8
      rev: v6.0.0.post1
      hooks:
          - id: pyproject-flake8
            additional_dependencies:
                [
                    "black==22.12.0",
                    "dlint==0.13.0",
                    "flake8-assertive==2.1.0",
                    "flake8-black==0.3.6",
                    "flake8-broken-line==0.6.0",
                    "flake8-bugbear==22.12.6",
                    "flake8-builtins==2.0.1",
                    "flake8-comprehensions==3.10.1",
                    "flake8-debugger==4.1.2",
                    "flake8-import-order==0.18.2",
                    "flake8-logging-format==0.9.0",
                    "flake8-pep3101==2.0.0",
                    "pep8-naming==0.13.3",
                    "pylint-django==2.5.3",
                ]

    - repo: https://github.com/frnmst/md-toc
      rev: 8.1.6
      hooks:
          - id: md-toc
            args: [-p, github, -u, -l6]
            files: '.*\.md'

    - repo: https://github.com/pre-commit/mirrors-prettier
      # sync with packages.json
      rev: v2.7.1
      hooks:
          - id: prettier
            types_or: ["markdown", "yaml"]
            files: '.*\.md'
