version: 2.1
orbs:
    utils: arrai/utils@1.21.1
    ruff: arrai/ruff@1.1.1
    pypi: arrai/pypi@3.1.0
    github: arrai/github@5.0.0
executors:
    python39:
        docker:
            - image: cimg/python:3.9
    python310:
        docker:
            - image: cimg/python:3.10
    python311:
        docker:
            - image: cimg/python:3.11
    python312:
        docker:
            - image: cimg/python:3.12
    python313:
        docker:
            - image: cimg/python:3.13
    python314:
        docker:
            - image: cimg/python:3.14
jobs:
    build:
        executor: python311
        resource_class: small
        steps:
            - checkout
            - run:
                name: "Install build requirements"
                command: |
                    pip install --user --upgrade build wheel
            - when:
                condition: << pipeline.git.tag >>
                steps:
                    - run:
                        name: "Verify scm tag matches software version"
                        command: |
                            DIST_VERSION=$(python -c 'with open("VERSION", "r") as f: print(f.readline().strip())')
                            if [ -z "${DIST_VERSION}" ] || [ "${DIST_VERSION}" != "${CIRCLE_TAG}" ]; then
                                echo "Git tag: ${CIRCLE_TAG} does not match the release version: ${DIST_VERSION}"
                                exit 1
                            fi
            - run:
                name: "Build Package"
                command: python -m build --wheel
            - save_cache:
                paths:
                    - ~/project/dist
                key: build-{{ arch }}
    install:
        parameters:
            executor:
                description: "Execution environment for the install test job."
                type: executor
                default: python311
        executor: <<parameters.executor>>
        resource_class: small
        steps:
            - restore_cache:
                keys:
                    - build-{{ arch }}
            - run:
                  name: "Install wheel"
                  command: pip install ~/project/dist/*.whl
            - run:
                  name: "Import library"
                  command: python -c 'from django_view_manager.utils.apps import UtilsConfig; from django_view_manager.utils.management.commands.makeviewmigration import Command'
    tests:
        parameters:
            executor:
                description: "Execution environment for the test job."
                type: executor
                default: python312
            django:
                description: "Django version for the test job."
                type: string
                default: "django_4.2"
        executor: <<parameters.executor>>
        circleci_ip_ranges: true
        resource_class: small
        steps:
            - checkout
            - utils/add_ssh_config
            - when:
                condition:
                    equal: [ main, << pipeline.git.branch >> ]
                steps:
                    - utils/make_status_shield:
                        status: running
                        color: lightblue
                    - utils/rsync_file:
                        file: ~/status.svg
                        remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
                        host: docs
            - run:
                name: "Install test requirements"
                command: pip install -r test_requirements_<<parameters.django>>.txt | cat; test ${PIPESTATUS[0]} -eq 0
            - run:
                name: "Run tests"
                command: coverage run --source='.' manage.py test
            - run:
                when: always
                command: |
                    coverage html
                    coverage report | grep -oP '^TOTAL.*\d' | awk '{print $NF}' >> /tmp/.coveragep
            - utils/rsync_folder:
                when: always
                folder: ./htmlcov/
                remote_folder: ${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}
                host: docs
            - run:
                name: "Create freeze file"
                when: always
                command: pip freeze > ~/pip.freeze
            - utils/rsync_file:
                when: always
                file: ~/pip.freeze
                remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.freeze
                host: docs
            - when:
                condition:
                    equal: [ main, << pipeline.git.branch >> ]
                steps:
                    - utils/make_coverage_shield:
                        when: always
                        link: "https://${DOCS_HOST}/${CIRCLE_PROJECT_REPONAME}/artifacts/${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}/"
                    - utils/rsync_file:
                        when: always
                        file: /tmp/coverage.svg
                        remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.coverage.svg
                        host: docs
                    - utils/make_status_shield:
                        when: on_success
                        status: passed
                        color: brightgreen
                    - utils/make_status_shield:
                        when: on_fail
                        status: failed
                        color: red
                    - utils/rsync_file:
                        when: always
                        file: ~/status.svg
                        remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
                        host: docs
workflows:
    test_and_build:
        jobs:
            - tests:
                name: python_3.9-django_4.2
                context: arrai-global
                executor: python39
                django: django_4.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.10-django_4.2
                context: arrai-global
                executor: python310
                django: django_4.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.10-django_5.1
                context: arrai-global
                executor: python310
                django: django_5.1
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.10-django_5.2
                context: arrai-global
                executor: python310
                django: django_5.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.11-django_4.2
                context: arrai-global
                executor: python311
                django: django_4.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.11-django_5.1
                context: arrai-global
                executor: python311
                django: django_5.1
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.11-django_5.2
                context: arrai-global
                executor: python311
                django: django_5.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.12-django_4.2
                context: arrai-global
                executor: python312
                django: django_4.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.12-django_5.1
                context: arrai-global
                executor: python312
                django: django_5.1
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.12-django_5.2
                context: arrai-global
                executor: python312
                django: django_5.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.13-django_5.1
                context: arrai-global
                executor: python313
                django: django_5.1
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.13-django_5.2
                context: arrai-global
                executor: python313
                django: django_5.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python_3.14-django_5.2
                context: arrai-global
                executor: python314
                django: django_5.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - build:
                name: build
                requires:
                    - python_3.9-django_4.2
                    - python_3.10-django_4.2
                    - python_3.10-django_5.1
                    - python_3.10-django_5.2
                    - python_3.11-django_4.2
                    - python_3.11-django_5.1
                    - python_3.11-django_5.2
                    - python_3.12-django_4.2
                    - python_3.12-django_5.1
                    - python_3.12-django_5.2
                    - python_3.13-django_5.1
                    - python_3.13-django_5.2
                    - python_3.14-django_5.2
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python39_install
                executor: python39
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python310_install
                executor: python310
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python311_install
                executor: python311
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python312_install
                executor: python312
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python313_install
                executor: python313
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python314_install
                executor: python314
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - pypi/upload_release:
                name: publish
                cache_key: build-{{ arch }}
                context: arrai-public-package-publishing
                requires:
                    - python39_install
                    - python310_install
                    - python311_install
                    - python312_install
                    - python313_install
                    - python314_install
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
            - github/create_release:
                name: release_on_github
                context: arrai-global
                requires:
                    - publish
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
    lint:
        jobs:
            - ruff/ruff_fixed_ip:
                  name: ruff
                  context: arrai-global
                  executor: python312
                  filters:
                      branches:
                          only:
                              - main
            - ruff/ruff:
                  name: ruff-no-badge
                  executor: python312
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
