# Generated by Django 3.2.17 on 2023-08-11 16:16

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BandInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024)),
                ("genre", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "band_info",
                "ordering": ("name",),
                "managed": False,
                "default_related_name": "musicians_bandinfo",
            },
        ),
        migrations.CreateModel(
            name="Bands",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024)),
                ("genre", models.CharField(max_length=1024)),
                ("formed", models.DateField()),
            ],
            options={
                "ordering": ("name",),
                "default_related_name": "bands",
            },
        ),
        migrations.CreateModel(
            name="BandMembers",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024)),
                ("active_member", models.BooleanField(default=True)),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="band_members",
                        to="musicians.bands",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "default_related_name": "band_members",
            },
        ),
    ]
