# Generated by Django 3.2.17 on 2023-08-11 16:17
# Modified using django-view-manager 1.0.4.  Please do not delete this comment.
import os

from django.db import migrations

sql_path = "tests/musicians/sql"
forward_sql_filename = "view-band_info-0002.sql"

with open(os.path.join(sql_path, forward_sql_filename), mode="r") as f:
    forwards_sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql="DROP VIEW IF EXISTS band_info;",
        ),
    ]
