# Generated by Django 3.2.17 on 2023-08-11 16:30
# Modified using django-view-manager 1.0.4.  Please do not delete this comment.
import os

from django.db import migrations

sql_path = "tests/musicians/sql"
forward_sql_filename = "view-band_info-latest.sql"
reverse_sql_filename = "view-band_info-0003.sql"

with open(os.path.join(sql_path, forward_sql_filename), mode="r") as f:
    forwards_sql = f.read()

with open(os.path.join(sql_path, reverse_sql_filename), mode="r") as f:
    reverse_sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0002_create_band_info_view"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql=reverse_sql,
        ),
    ]
