# Generated by Django 3.2.17 on 2023-08-11 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0003_add_founded_date"),
        ("musicians", "0003_add_member_count"),
    ]

    operations = []
