# Generated by Django 3.2.17 on 2023-08-09 15:08

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCalculations",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("markup_price", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                "db_table": "store_productcalculations",
                "managed": False,
                "default_related_name": "calculations",
            },
        ),
        migrations.CreateModel(
            name="PurchasedProductCalculations",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profit", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                "db_table": "store_purchasedproductcalculations",
                "managed": False,
                "default_related_name": "calculations",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("markup_percentage", models.IntegerField()),
            ],
            options={
                "ordering": ("name",),
                "default_related_name": "products",
            },
        ),
        migrations.CreateModel(
            name="PurchasedProducts",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="store.products"
                    ),
                ),
            ],
            options={
                "ordering": ("product__name",),
                "default_related_name": "order_items",
            },
        ),
    ]
