# Generated by Django 3.2.17 on 2023-08-09 15:08
# Modified using django-view-manager 1.0.4.  Please do not delete this comment.
import os

from django.db import migrations

sql_path = "tests/store/sql"
forward_sql_filename = "view-store_purchasedproductcalculations-latest.sql"

with open(os.path.join(sql_path, forward_sql_filename), mode="r") as f:
    forwards_sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_create_product_calculations_view"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql="DROP VIEW IF EXISTS store_purchasedproductcalculations;",
        ),
    ]
